--- 
- hosts: "*"
  become: false
  gather_facts: false
  tasks:

  - name: Getting latest stuff from github repository
    git:
      # repo: git@github.com:athul76/zabbix_maintanence.git
      repo: https://github.com/athul76/zabbix_maintanence.git
      dest: /repo/zabbix-maintenance
      version: master
      force: yes

  - name: Changing perm of "set_maintenance.sh", adding "+x"
    file: dest=/repo/zabbix_maintenance/scripts/set_maintenance.sh mode=a+x

  - name: run scripts locally on deploy server to read csv, set maintenance in Zabbix, log result and upload back to git repo
    shell: /repo/zabbix-maintenance/scripts/set_maintenance.sh
    args:
        chdir: /repo/zabbix-maintenance/scripts/